language: node_js
node_js: 
  - "stable"
script: npm test
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $jsdocsAccess 
  keep_history: true
  on:
    branch: master